name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH in EC2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Remote SSH in EC2
        run: |
          ssh -i private_key.pem -o StictHostKeyChecking=no ${{ secrets.EC2_IP }} 
          echo "Deploying to Ec2"
