name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Code
        uses: actions/checkout@v2

      - name: Setup SSH in EC2
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Remote SSH in EC2
        run: |
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_IP }} 

      - name: Deploy to EC2
        run: |
          cd desktop
          if [ ! -d "animation-generation" ]; then
            git clone https://github.com/sdt03/animation-generation.git 
          fi

          cd animation-generation
          git pull origin main
          cd sandbox/app
          source venv/bin/activate
          pip install -r requirements.txt
          python main.py
