name: Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Remote SSH in EC2
        run: |
          ssh -i "${{ secrets.SSH_PRIVATE_KEY }}" -o StrictHostKeyChecking=no ${{ secrets.EC2_IP }} << 'EOF'
          echo "Deploying to EC2 instance..."
      