on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment: production 
    
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
    
    steps:
      - name: SSH into EC2
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@56.228.36.207

      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Change working directory to sandbox
        run: cd animation-generation/sandbox
        
      - name: Create venv and install dependencies
        working-directory: ./animation-generation/sandbox/app
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          
      - name: Run the app
        run: |
          source ../venv/bin/activate
          python main.py
        
      
          
      